import { getSession, useSession, signIn, signOut } from "next-auth/react"
import Head from "next/head"
import Link from "next/link"
import { useEffect, useState } from "react"
import { Asterisk, Bootstrap, FiletypeJava, FiletypeJs, List, Microsoft } from "react-bootstrap-icons"
import AppNavbar from "../../lib/components/AppNavbar"
import SideNav from "../../lib/components/Staff/Navbar/SideNav"
import StaffNav from "../../lib/components/StaffNav"
import StaffNavTest from "../../lib/components/StaffNav/StaffNavTest"

export default function StaffDashboard(){
    const { data: session } = useSession()

    return <div>
        <Head>
            <title>Dashboard</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="position-sticky sticky-lg-top pt-0 fixed-height-overflow mb-3">
            <StaffNav/>
        </div>

        <div className="container-fluid">    
            <div className="col-12 col-lg-12 px-0">
                <div className="row justify-content-center">
                    <div className="col-12 col-lg-12">
                        <h3 className="text-muted">
                            FAQ
                        </h3>
                    </div>

                    <div className="col-12 col-lg-12">
                        <ul className="navbar-nav-scroll navbar-nav me-auto mb-2 mb-lg-2 d-flex flex-row text-nowrap">
                            <li className="nav-item pe-3">
                            <Link href={'/staff/mahasiswa'}><a className="nav-link">Mahasiswa</a></Link>
                            </li>
                            <li className="nav-item pe-3 ">
                                <a className="nav-link">Kebijakan Privasi</a>
                            </li>
                            <li className="nav-item pe-3 ">
                                <a className="nav-link">Syarat dan Ketentuan Produk</a>
                            </li>
                            <li className="nav-item pe-3 ">
                                <a className="nav-link">Persyaratan Jasa</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div className="container-fluid">
            <div className="row">
                <SideNav/>
                
                <div className="col-lg-10 col-md-10 col-sm-12">
                    <div className="row px-3 ps-3 p-2">
                        <div className="card">
                            <div className="row py-3">
                                <div className="col-sm-12 col-md-12 col-lg-6 mb-3">
                                    <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">Mahasiswa</h5>
                                        <p className="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                    </div>
                                </div>
                                <div className="col-sm-12 col-md-12 col-lg-6 mb-3">
                                    <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">Special title treatment</h5>
                                        <p className="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                    </div>
                                </div>
                                <div className="col-sm-12 col-md-12 col-lg-6 mb-3">
                                    <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">Special title treatment</h5>
                                        <p className="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                    </div>
                                </div>
                                <div className="col-sm-12 col-md-12 col-lg-6 mb-3">
                                    <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">Special title treatment</h5>
                                        <p className="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                    </div>
                                </div>
                                <div className="col-sm-12 col-md-12 col-lg-6 mb-3">
                                    <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">Special title treatment</h5>
                                        <p className="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                    </div>
                                </div>
                                <div className="col-sm-12 col-md-12 col-lg-6 mb-3">
                                    <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">Special title treatment</h5>
                                        <p className="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                    </div>
                                </div>
                                <div className="col-sm-12 col-md-12 col-lg-6 mb-3">
                                    <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">Special title treatment</h5>
                                        <p className="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                    </div>
                                </div>
                                <div className="col-sm-12 col-md-12 col-lg-6 mb-3">
                                    <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">Special title treatment</h5>
                                        <p className="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                    </div>
                                </div>
                                <div className="col-sm-12 col-md-12 col-lg-6 mb-3">
                                    <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">Special title treatment</h5>
                                        <p className="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                    </div>
                                </div>
                                <div className="col-sm-12 col-md-12 col-lg-6 mb-3">
                                    <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">Special title treatment</h5>
                                        <p className="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                    </div>
                                </div>
                                <div className="col-sm-12 col-md-12 col-lg-6 mb-3">
                                    <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">Special title treatment</h5>
                                        <p className="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                    </div>
                                </div>
                                <div className="col-sm-12 col-md-12 col-lg-6 mb-3">
                                    <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">Special title treatment</h5>
                                        <p className="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                    </div>
                                </div>
                                <div className="col-sm-12 col-md-12 col-lg-6 mb-3">
                                    <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">Special title treatment</h5>
                                        <p className="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                    </div>
                                </div>
                                <div className="col-sm-12 col-md-12 col-lg-6 mb-3">
                                    <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">Special title treatment</h5>
                                        <p className="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                    </div>
                                </div>
                                <div className="col-sm-12 col-md-12 col-lg-6 mb-3">
                                    <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">Special title treatment</h5>
                                        <p className="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                    </div>
                                </div>
                                <div className="col-sm-12 col-md-12 col-lg-6 mb-3">
                                    <div className="card">
                                    <div className="card-body">
                                        <h5 className="card-title">Special title treatment</h5>
                                        <p className="card-text">With supporting text below as a natural lead-in to additional content.</p>
                                    </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

export async function getServerSideProps(context) {
    const session = await getSession(context)

    if (!session){
        return {
            redirect: {
                permanent: false,
                destination: "/"
            }
        }
    }

    return {
        props: {
            session,
        }
    }
}