import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import clientPromise from '../lib/mongodb'
import { getSession, useSession, signIn, signOut } from "next-auth/react"
import Link from 'next/link'
import AppNavbar from '../components/navbar/appNavbar'

export default function Home({isConnected}) {
  const { data: session } = useSession()
  // if(session){
  //   console.log(session.user)
  // }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppNavbar />

      <main className={styles.main}>

        <h1>{!session ? '': <Link href={'/staff'}><a style={{color: 'blue', textDecoration: 'underline'}}>Staff</a></Link>}</h1>

        <h1>{!session ? '': <a style={{color: 'blue'}}>{session.user.name}</a>} Hello</h1>

        {isConnected ? (
          <h2 className="subtitle">You are connected to MongoDB</h2>
        ) : (
          <h2 className="subtitle">
            You are NOT connected to MongoDB. Check the <code>README.md</code>{' '}
            for instructions.
          </h2>
        )}

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      <footer className={styles.footer}>
        <Link href={'/about'}><a style={{color: 'blue'}}>Ikbal Yaduar</a></Link>
      </footer>
    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context)

  try {
    await clientPromise
    // `await clientPromise` will use the default database passed in the MONGODB_URI
    // However you can use another database (e.g. myDatabase) by replacing the `await clientPromise` with the following code:
    //
    // `const client = await clientPromise`
    // `const db = client.db("myDatabase")`
    //
    // Then you can execute queries against your database like so:
    // db.find({}) or any of the MongoDB Node Driver commands

    return {
      props: { isConnected: true },
    }
  } catch (e) {
    console.error(e)
    return {
      props: { isConnected: false },
    }
  }
}